name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prepare
      run: |
        sudo apt update
        sudo apt install libgl1-mesa-dev xorg-dev -y
        mkdir bin

    - name: Build linux
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o bin/picture-shuffler_linux main.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin

  build-pi:
    runs-on: ubuntu-latest
    container:
      image: "balenalib/raspberry-pi"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prepare
      run: |
        sudo apt update
        sudo apt install libgl1-mesa-dev xorg-dev -y
        mkdir bin

    - name: Build pi
      run: |
        go env
        GOOS=linux GOARCH=arm64 go build -v -o bin/picture-shuffler_pi main.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin
  
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prepare
      run: |
        mkdir bin

    - name: Build darwin
      run: |
        GOOS=darwin GOARCH=amd64 go build -v -o bin/picture-shuffler_darwin main.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Prepare
      run: |
        mkdir bin

    - name: Build windows
      run: |
        go build -v -o bin/picture-shuffler.exe main.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin
