name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Prepare
      run: |
        sudo apt update
        sudo apt install libgl1-mesa-dev xorg-dev -y
        mkdir bin

    - name: Test
      run: |
        go test ./... -v

    - name: Build ubuntu
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o bin/picture-shuffler_linux main.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin

  build-pi:
   runs-on: ubuntu-latest
   container:
     image: "debian:buster"
   steps:
   - uses: actions/checkout@v2

   - name: Set up Go
     uses: actions/setup-go@v4
     with:
       go-version-file: go.mod
       check-latest: true

   - name: Prepare
     run: |
       apt update
       apt install libgl1-mesa-dev xorg-dev ca-certificates build-essential -y
       mkdir bin

   - name: Test
     run: |
       go test ./... -v

   - name: Build debian
     run: |
       go env
       GOOS=linux GOARCH=amd64 go build -v -o bin/picture-shuffler_pi main.go

   - uses: actions/upload-artifact@v2
     with:
       name: binaries
       path: bin
  
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Prepare
      run: |
        mkdir bin

    - name: Test
      run: |
        go test ./... -v

    - name: Build darwin
      run: |
        GOOS=darwin GOARCH=amd64 go build -v -o bin/picture-shuffler_darwin main.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Prepare
      run: |
        mkdir bin

    - name: Test
      run: |
        go test ./... -v

    - name: Build windows
      run: |
        go build -v -o bin/picture-shuffler.exe main.go

    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin

  dependabot:
    needs: [ build-linux, build-pi, build-mac, build-windows ]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
